# MADE BY:
#  __    __                                          __        __  __  __                     
# /  |  /  |                                        /  |      /  |/  |/  |                    
# $$ |  $$ |  ______   _______    ______    ______  $$ |____  $$/ $$ |$$/   _______  __    __ 
# $$  \/$$/  /      \ /       \  /      \  /      \ $$      \ /  |$$ |/  | /       |/  |  /  |
#  $$  $$<  /$$$$$$  |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$$  |$$ |$$ |$$ |/$$$$$$$/ $$ |  $$ |
#   $$$$  \ $$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |$$ |$$ |      $$ |  $$ |
#  $$ /$$  |$$$$$$$$/ $$ |  $$ |$$ \__$$ |$$ |__$$ |$$ |  $$ |$$ |$$ |$$ |$$ \_____ $$ \__$$ |
# $$ |  $$ |$$       |$$ |  $$ |$$    $$/ $$    $$/ $$ |  $$ |$$ |$$ |$$ |$$       |$$    $$ |
# $$/   $$/  $$$$$$$/ $$/   $$/  $$$$$$/  $$$$$$$/  $$/   $$/ $$/ $$/ $$/  $$$$$$$/  $$$$$$$ |
#                                         $$ |                                      /  \__$$ |
#                                         $$ |                                      $$    $$/ 
#                                         $$/                                        $$$$$$/

#First range {default: ping <= 50 & ping > 0} {Ping Status: Excellent}
Range_1:
  less_than: 50
  greater_than: 0
  message: "§bExcellent"
#Second range {default: ping <= 100 & ping > 50 } {Ping Status: Good}
Range_2:
  less_than: 100
  greater_than: 50
  message: "§aGood"
#Second range {default: ping <= 200 & ping > 100 } {Ping Status: Ok}
Range_2:
  less_than: 200
  greater_than: 100
  message: "§eOk"
#Second range {default: ping <= 500 & ping > 300 } {Ping Status: Poor}
Range_2:
  less_than: 500
  greater_than: 300
  message: "§cPoor"
#Second range {default: ping <= 5000 & ping > 500 } {Ping Status: Extremely Poor}
Range_2:
  less_than: 5000
  greater_than: 500
  message: "§cExtremely Poor"
